// Generated by scripts/portraits.ts (npm run portraits). Do not edit by hand.
export const MEN_PORTRAITS: readonly string[] = [
  "/fighters/m-01.jpg",
  "/fighters/m-02.jpg",
  "/fighters/m-03.jpg",
  "/fighters/m-04.jpg",
  "/fighters/m-05.jpg",
  "/fighters/m-06.jpg"
];
export const WOMEN_PORTRAITS: readonly string[] = [
  "/fighters/w-01.jpg",
  "/fighters/w-02.jpg",
  "/fighters/w-03.jpg",
  "/fighters/w-04.jpg"
];
/** Shown for players who haven't chosen a picture. */
export const PLAYER_PLACEHOLDER: string | undefined = "/fighters/o-01.jpg";
