/**
 * Rebuilds the fighter portraits from the source images.
 *
 *   npm run portraits
 *
 * Sources: public/avatars/m-*.{png,jpg,jpeg,webp} (men) and w-* (women),
 * any size. Other files there are ignored. Each is cut as a square from the top (keeps the head, drops the
 * bottom strip where AI images tend to put garbled lettering), resized to
 * 600px and saved as a JPEG in public/fighters. Web copies whose source was
 * deleted are removed, and src/lib/portraits.generated.ts is rewritten, so
 * adding or deleting a source image and re-running is all it takes.
 * Uses macOS `sips`.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { basename, extname, join } from "node:path";
import { tmpdir } from "node:os";

const SOURCE = "public/avatars";
const OUT = "public/fighters";
const LIST = "src/lib/portraits.generated.ts";
const SIZE = 600;

const sips = (...args: string[]) => execFileSync("sips", args, { encoding: "utf8" });
const dimension = (file: string, key: string) => Number(/:\s*(\d+)/.exec(sips("-g", key, file).split("\n").find((l) => l.includes(key))!)![1]);

mkdirSync(OUT, { recursive: true });
const sources = readdirSync(SOURCE)
  .filter((f) => /^[mw]-[\w-]+\.(png|jpe?g|webp)$/i.test(f))
  .sort();

const made = new Set<string>();
for (const file of sources) {
  const src = join(SOURCE, file);
  const name = `${basename(file, extname(file))}.jpg`;
  const width = dimension(src, "pixelWidth");
  const height = dimension(src, "pixelHeight");
  const side = Math.floor(Math.min(width, height * 0.9));
  const x = Math.floor((width - side) / 2);
  const crop = join(tmpdir(), `portrait-${process.pid}.png`);
  sips("-c", String(side), String(side), "--cropOffset", "0", String(x), src, "--out", crop);
  sips("-Z", String(SIZE), "-s", "format", "jpeg", "-s", "formatOptions", "82", crop, "--out", join(OUT, name));
  rmSync(crop, { force: true });
  made.add(name);
  console.log(`${file} (${width}x${height}) -> ${OUT}/${name}`);
}

for (const file of readdirSync(OUT)) {
  if (!made.has(file)) {
    rmSync(join(OUT, file));
    console.log(`removed ${OUT}/${file} (no source)`);
  }
}

const listOf = (prefix: string) => [...made].filter((f) => f.startsWith(prefix)).sort().map((f) => `/fighters/${f}`);
const men = listOf("m-");
const women = listOf("w-");
writeFileSync(
  LIST,
  `// Generated by scripts/portraits.ts (npm run portraits). Do not edit by hand.\n` +
    `export const MEN_PORTRAITS: readonly string[] = ${JSON.stringify(men, null, 2)};\n` +
    `export const WOMEN_PORTRAITS: readonly string[] = ${JSON.stringify(women, null, 2)};\n`
);
console.log(`${men.length} men, ${women.length} women -> ${LIST}`);
if (!existsSync(LIST)) process.exit(1);
